### ISSUE TITLE
[Feature Request] Physics Groups

### ISSUE THREAD

**Issue by thinknathan** [britzl/boom#3]
## Suggestion

Allow setting physics group when adding Area component.

## Background

I have a game with a large number of enemies moving every frame. When they move close to each other, they quickly overwhelm the limit of max collisions and messages are lost.

In my case, the enemies don't need to interact with each other, they only need to have collision with the player.

Should boom have a way to optimize for this situation? For example, should the API allow you to set a custom physics group when adding the area component?

## Alternatives Considered

Is what I'm describing already possible with the standard Defold API?

I tried setting the physics group after an object is created, but I get the error `The component could not be found`.

```lua
local enemyObj = add({
	area({shape = "auto"}),
	...
})
physics.set_group(enemyObj.id, "enemy")
```

Non-physics commands like `go.get_property` work fine on the same object. I'm sorry if I'm misunderstanding the fundamentals here.

**Comment by britzl** [comment]
> they quickly overwhelm the limit of max collisions and messages are lost

You can increase this limit: https://defold.com/manuals/project-settings/#max-collisions. Would that help in your case?

> I tried setting the physics group after an object is created, but I get the error `The component could not be found`

The physics shape is on a child game object, and the id is not exposed:

https://github.com/britzl/boom/blob/main/boom/components/area.lua#L54

 I should perhaps add it to the object so that users can interact with the shape directly.

**Comment by thinknathan** [comment]
Thanks for following up. I appreciate the suggestion to increase the collisions limit, but even after increasing it to 8x the default, there are still some cases where I hit the limit. I'm also worried about the performance impact of so many physics events every frame.

Exposing the ID of the shape sounds like a good solution for corner cases like mine.

**Comment by britzl** [comment]
> Exposing the ID of the shape sounds like a good solution for corner cases like mine.

Cool. Objects with an area component will now have an `area_url` which is the URL to the collision object. You can use physics.set_group() and set_maskbit() with that URL.

Fixed in https://github.com/britzl/boom/commit/fc1e1c0a840d22913affa3f8592e3b2fbe1bb128
